# Generated by Django 2.0.8 on 2018-10-10 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothek', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_name',
            new_name='title',
        ),
    ]
