# Generated by Django 2.0.8 on 2018-10-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothek', '0005_auto_20181010_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author',
        ),
        migrations.RemoveField(
            model_name='author',
            name='pub_date',
        ),
    ]
