# Generated by Django 2.0.8 on 2018-10-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothek', '0006_auto_20181010_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
