# Generated by Django 2.1.1 on 2018-10-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothek', '0012_book_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_check_out',
            field=models.BooleanField(default=True),
        ),
    ]
