# Generated by Django 2.1.1 on 2018-10-13 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothek', '0013_book_user_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_check_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
